---
title: "aoa"
author: "Joshua Johnson"
date: "1/7/2021"
output:
  pdf_document: default
  html_document: default
---

<!-- Packages -->

<!-- Data load -->
```{r aob qPCR load, echo=FALSE, warning=FALSE, message = FALSE}
# Loading bay
qpcr <- 
      read_delim("C:/Users/jjohn/OneDrive/MScthesis/data/qPCR/aoa.csv",",",) #gene copy numbers from qpcr instrument
    dna <- 
      read_delim("C:/Users/jjohn/OneDrive/MScthesis/data/dna.csv",",",) # dna concentration of samples
    trt <-
      read_delim("C:/Users/jjohn/OneDrive/MScthesis/data/treatment_factors.csv",",",) #treatment index

# Variable changing room 
    qpcr$id <- as.factor(qpcr$id)
    dna$id <- as.factor(dna$id)
    trt$time[trt$time == "t2"] <- "1"
    trt$time[trt$time == "t3"] <- "2"
    
    #trt <- trt %>%
      #convert_as_factor(id,fert,fung,block,time,row,treatment,subject) # easier when more than one needs to change
    trt$id <- as.factor(trt$id)

# table with standard curve parameters
    # can be printed with kbl easy 
standard_aoa <- 
      read_delim("data/aoa_standard.csv",",",)


```    
    
    
```{r recalibration, echo=FALSE, message=FALSE}
# Standard curve based on '[Type:Soil | Timepoint: T3] standard results

  standard_curve <- 
    read_delim("C:/Users/jjohn/OneDrive/MScthesis/data/qPCR/aoa_standard_curve.csv",",",)

# Gettin an exacter model equation
  model <- lm(ct ~ qty_log10, data = standard_curve)
  model
  
#Coefficients:
#(Intercept)    qty_log10  
#     37.245       -3.367
  
# Recalculating the quantity values based on the standard curve in '[Type:Soil | Timepoint: T3]

  # Load the data 
  
  std <- qpcr %>%
    filter(id == "Standard 2")%>%
    select(type,time,id,ct)%>%
    group_by(time,type)%>%
    get_summary_stats(ct, type = "mean_sd")
  
# We use the Standard 2 as an interrun calibrator and the Standard 2 of [Type:Soil | Timepoint: T3] is the 1.0 (100%)
  
  #Value is [Type:Soil | Timepoint: T3] 13.188
  
 std <- std %>%
    mutate(corr = mean - 12.472 )%>%
    select(time, type, corr)
 
 write_csv(std, "corr_factor.csv")
 
 qpcr <- 
   read_delim("C:/Users/jjohn/OneDrive/MScthesis/data/qPCR/aoa.csv",",",)%>%
   filter(id!="Standard 2")%>%
   select(time,type,id,ct)

 
 
 qpcr <- qpcr %>% 
   inner_join(std, by = c("time" = "time", "type" = "type"))%>%
   mutate(ct_corr = ct + corr)%>%
   select(time,type,id,ct_corr)%>%
   mutate(qty= 10^((ct_corr-37.245)/-3.367)) #enter intercept and slope of standard curve u want to calibrate on here
  
# Recalibration on new standard curve done
 rm(std)
 rm(standard_curve)
 rm(model)
  
```

<!-- Data mangling -->
```{r Averaging technical replicates/ Resetting dilutions aoa, echo=FALSE, warning=FALSE, message = FALSE}
# Summary statistics
  summary <- qpcr %>%
    group_by(type, id)%>%                                    
    summarise(
      n=n(),
      avg.qty = mean(qty, na.rm=TRUE),
      sd.qty=sd(qty, na.rm = TRUE) 
    )%>% 
    ungroup()
 rm(qpcr)
 
# Join DNA conc. and summary qty for later calculations  
 joined <- summary %>% 
   inner_join(dna, by = c("id" = "id", "type" = "type"))%>% 
   rename(dna_conc= value)
 rm(summary)
 rm(dna)
 
#Normalize quantity values
  # Reset dilution
  # Normalize on 1 ul (8 ul template used in one well)
  # Normalize on 1 ng DNA (divide by DNA conc. per ng)
  # Index created: averaged quantity value (from technical replicates) for each replicate
 
   calc <- joined %>%
     mutate(qty_undil=avg.qty*20)%>% 
     mutate(qty_ul=qty_undil/8)%>% 
     mutate(qty_ng=qty_ul/dna_conc)
   
  # index <- calc  %>% 
    #inner_join(trt, by = c("id" = "id"))%>%
   # arrange(type, treatment)
 # rm(joined)
   
  # From calc we extract the calculated values into a new tibble and remove calc 
    # There are other columns in calc which contain unwanted information, hence the new tibble
    # You could also set the unwanted columns to NULL and work further with calc 
   fin <- calc %>% 
     select(type,id, qty_ng) %>% 
     mutate(unit = "GeneCopies/ngDNA")
  rm(calc)
  
  # Add descriptors (another table) for treatment factors
  
  genecopy <- fin %>% 
   inner_join(trt, by = c("id" = "id"))
  
  rm(trt)
  rm(fin)
  
# Finished, we now have a tibble called 'genecopy' which includes the gene copy numbers per ng DNA
  # Index is a copy of all average qty values (avg of technical replicates) for each replicate and is normalized on ng DNA
```

<!-- Summary Statistics -->

```{r summary stastics aoa, echo=FALSE, warning=FALSE, message = FALSE}
 summary <- genecopy %>%
  group_by(type,time,fert,fung) %>%
  get_summary_stats(qty_ng, type = "mean_sd")%>%
  select(type, time, fert, fung, mean, sd)

genecopy$treatment[genecopy$treatment == "H00"] <- "Control"
genecopy$treatment[genecopy$treatment == "H01"] <- "Fert"
genecopy$treatment[genecopy$treatment == "HP0"] <- "Fung + GroRe"
genecopy$treatment[genecopy$treatment == "HP1"] <- "Full"


```
<!-- Summary Statistics
*intermediate data is named here different because of debugging process -->

```{r dabestr estimation aoa, echo=FALSE, message = FALSE}
library(dabestr)

my_theme <- theme_classic() + theme(axis.title.y = element_text(size=10))
# soil
wrk <- genecopy %>%
  filter(type == "soil") %>%
  convert_as_factor(time,subject)

wrk.dabest <- 
  wrk %>%
  dabest(treatment, qty_ng, 
         idx = c("Control", "Fert", "Fung + GroRe", "Full"))

# The summary indicates this is a paired comparison. 
wrk.diff <- mean_diff(wrk.dabest)
soilaoaTable <- wrk.diff

soilaoa <- plot(wrk.diff, 
     color.column = time,
     effsize.ylim = c(-1500, 1500),
     slopegraph = TRUE,
     rawplot.ylabel = "Gene copy numbers \n [ng DNA]",
     theme=my_theme
    )
```


```{r rhizo}
#rhizo
wrk <- genecopy %>%
  filter(type == "rhizo") %>%
  convert_as_factor(time,subject)

wrk$id <- as.numeric(wrk$id)
wrk <- filter(wrk, subject != "12")

wrk.dabest <- 
  wrk %>%
  dabest(treatment, qty_ng, 
         idx = c("Control", "Fert","Fung + GroRe", "Full")
         )


# The summary indicates this is a paired comparison. 
wrk.diff <- mean_diff(wrk.dabest)
rhizoaoaTable <- wrk.diff

rhizoaoa <- plot(wrk.diff, 
     color.column = time,
     effsize.ylim = c(-1000, 1000),
     slopegraph = TRUE,
     rawplot.ylabel = "Gene copy numbers \n [ng DNA]"
    )
```

