<!-- Data for chemical analysis is calculated here -->

```{r data / labs load, echo=FALSE, results='hide', warning = FALSE, message = FALSE}
library(tidyverse)
library(ggplot2)
# Read data as tibble (tidyverse)

  chem <- 
      read_delim("C:/Users/jjohn/OneDrive/MScthesis/data/chemanalysis.csv",",",) %>%
      filter (crop == "W") #only need W for my thesis

# Correct Variable types here 

  chem$value <- as.numeric(chem$value)
  chem$id    <- as.factor(chem$id)
  chem$treatment <- as.factor(chem$treatment)

#Summary statistics 

  summary <- chem %>%
    group_by(type, timepoint, id, treatment)%>%                     
    summarise(
      n = n(),
      avg = mean(value),
      sd = sd(value),
      med = median(value),
      min = min(value),
      max = max(value),
    )
  
  # Change label names here (Abbreviation index)
  
   labs <- c(
     c_t= "Total Carbon",
     n_t="Total Nitrogen",
     nit = "Nitrate ()",
     amo = "Ammonium (",
     ph = "pH",
     H00 = "Control",
     H01 = "Fertilizer",
     HP0 = "Fung+GroReg",
     HP1 = "Full",
     t2 = "t1",
     t3 = "t2",
     timepoint = "Timepoint"
            )
   
```


```{r soil.nitrogen, echo=FALSE}

  # Plant-available nitrogen
  #Nitrate
  reduced <- filter(summary,id == "nit") #filter so we got what we need
  
  plot.nit <- ggplot(reduced,aes(timepoint,avg,fill=timepoint))+
    geom_bar(stat="identity", 
             position=position_dodge(),
             show.legend = FALSE
             )+
    geom_errorbar(aes(ymin=avg-sd, ymax=avg+sd), width=.2,
                 position=position_dodge(.9))+
    ylab("mg in 100g wet soil")+
    facet_grid(treatment~id,
               scales="free",
               labeller = labeller(id = labs, treatment = labs, timepoint = labs)
               )+
    NULL
  #Ammonium
  reduced <- filter(summary, id == "amo" )
  plot.amo <- ggplot(reduced,aes(timepoint,avg,fill=timepoint))+
    geom_bar(stat="identity", 
             position=position_dodge(),
             show.legend = FALSE
             )+
    geom_errorbar(aes(ymin=avg-sd, ymax=avg+sd), width=.2,
                 position=position_dodge(.9))+
    ylab("mg in 100g wet soil")+
    facet_grid(treatment~id,
               scales="free",
               labeller = labeller(id = labs, treatment = labs, timepoint = labs),
               )+
    NULL
  library(ggpubr)
  

```


```{r ct/nt soil, echo=FALSE, include=FALSE, message=FALSE}
# soil
  
  reduced <- filter(summary, type =="soil", id == "c_t" | id == "n_t")
  
  plot.ctnt <- ggplot(reduced,aes(treatment,avg,fill=treatment))+
    geom_bar(stat="identity", 
             position=position_dodge()
             )+
    geom_errorbar(aes(ymin=avg-sd, ymax=avg+sd), width=.2,
                 position=position_dodge(.9))+
    facet_wrap(~id,
               scales="free",
               labeller = labeller(id = labs)
               ) +
    ylab("[% of dried soil sample]")+
    labs("Concentration of carbon and nitrogen in dried soil")+
    NULL
  library(cowplot)
   plot.nitamo<- plot_grid(plot.nit + theme(legend.position="none"),
                         plot.amo + theme(legend.position="none")
                         ,labels = c('A', 'B')
                         )
   soil <- plot_grid(plot.nitamo,
            plot.ctnt,
            labels = c('', 'C'),
            ncol = 1, nrow = 2,
            rel_heights = c(2,1))
```

```{r ct/nt root, echo=FALSE}
# root
  
   #c_t
  reduced <- filter(summary, type =="root", id == "c_t" )
  
  plot.ct.rt <- ggplot(reduced,aes(timepoint,avg,fill=timepoint))+
    geom_bar(stat="identity", 
             position=position_dodge()
             )+
    geom_errorbar(aes(ymin=avg-sd, ymax=avg+sd), width=.2,
                 position=position_dodge(.9))+
     facet_grid(treatment~id,
               scales="free",
               labeller = labeller(id = labs, treatment = labs, timepoint = labs),
               )+
    ylab("[% of dried root sample]")
  
  #n_t
  reduced <- filter(summary, type =="root", id == "n_t" )
  plot.nt.rt <- ggplot(reduced,aes(timepoint,avg,fill=timepoint))+
    geom_bar(stat="identity", 
             position=position_dodge()
             )+
    geom_errorbar(aes(ymin=avg-sd, ymax=avg+sd), width=.2,
                 position=position_dodge(.9))+
     facet_grid(treatment~id,
               scales="free",
               labeller = labeller(id = labs, treatment = labs, timepoint = labs),
               )+
    ylab("[% of dried root sample]")
  
  root<- plot_grid(plot.ct.rt + theme(legend.position="none"),
                         plot.nt.rt + theme(legend.position="none")
                         ,labels = c('A', 'B')
                         )
  
 
```

```{r ph soil, echo=FALSE}

  # I added a title here to get the facet_wrap title 
  
  reduced <- filter(summary, id == "ph")
  reduced$title <- "pH"
  
  plot.ph <- ggplot(reduced,aes(treatment,avg,fill=treatment))+
    geom_bar(stat="identity", 
             position=position_dodge()
             )+
    ylab(expression("-log [H"^"+"*"]"))+
    labs(title = "Total carbon and nitrogen content in dried roots")+
    geom_errorbar(aes(ymin=avg-sd, ymax=avg+sd), width=.2,
                 position=position_dodge(.9))+
    facet_wrap(~title)+
    NULL

    
```





